/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinFinderRouteImport } from './routes/skin-finder'
import { Route as IndexRouteImport } from './routes/index'

const SkinFinderRoute = SkinFinderRouteImport.update({
  id: '/skin-finder',
  path: '/skin-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skin-finder': typeof SkinFinderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skin-finder': typeof SkinFinderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skin-finder': typeof SkinFinderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skin-finder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skin-finder'
  id: '__root__' | '/' | '/skin-finder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkinFinderRoute: typeof SkinFinderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skin-finder': {
      id: '/skin-finder'
      path: '/skin-finder'
      fullPath: '/skin-finder'
      preLoaderRoute: typeof SkinFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkinFinderRoute: SkinFinderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
